version: '3.9'
services:
  api:
    build: .
    command: npm run start
    restart: always
    container_name: augeias_post_api
    image: augeias_post_api
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "7776:3000"

